Patch modcholesky to fix Rust 1.94 compilation
Summary:
Since {D95458261}:

```lang=log,counterexample
Action failed: fbsource//third-party/rust/vendor/modcholesky:0.1.4 (rustc check)
error[E0309]: the parameter type `T` may not live long enough
  --> third-party/rust/vendor/modcholesky-0.1.4/src/utils.rs:76:9
   |
73 | pub fn index_of_largest_abs<'a, T>(c: &ndarray::ArrayView1<T>) -> usize
   |                             -- the parameter type `T` must be valid for the lifetime `'a` as defined here...
...
76 |         std::cmp::PartialOrd + num::traits::Signed + Clone,
   |         ^^^^^^^^^^^^^^^^^^^^ ...so that the reference type `&'a T` does not outlive the data it points at
   |
help: consider adding an explicit lifetime bound
   |
73 | pub fn index_of_largest_abs<'a, T: 'a>(c: &ndarray::ArrayView1<T>) -> usize
   |                                  ++++
```

Reviewed By: capickett

Differential Revision: D95991664

fbshipit-source-id: 9900730e2006e16a42d8e9bed55c70dbe845c1a3