Delete read of lib.rs after thrift compiler execution
Summary:
This fixes failures like the following in `oss-eden-linux-getdeps-nosystem`. Since D54710352, a lib.rs output is no longer produced by Thrift's Rust code generator (the crate roots are types.rs, client.rs, server.rs). Separately, since D37145290, there is no reason for `run_compiler` to read a lib.rs or any other output file into memory.

```lang=text,counterexample
error: failed to run custom build command for `just_knobs_struct_services v0.1.0 (/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build/rust-shed/source/shed/justknobs_stub/cached_config_thrift_struct/services)`
Caused by:
  process didn't exit successfully: `/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build/rust-shed/release/build/just_knobs_struct_services-3270f7c2e8ff12fd/build-script-thrift_build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=thrift_build.rs
  cargo:rerun-if-env-changed=THRIFT
  cargo:rerun-if-env-changed=PATH
  cargo:rerun-if-changed=/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/bin/thrift1
  cargo:rerun-if-changed=../just_knobs.thrift
  --- stderr
  thread 'main' panicked at shed/justknobs_stub/cached_config_thrift_struct/services/thrift_build.rs:66:20:
  Failed while running thrift compilation: Thrift has successfully run, but the resulting '/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build/rust-shed/release/build/just_knobs_struct_services-0fde1c0be116e4b5/out/lib.rs' file is missing, command: 'Command {
      program: "/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/bin/thrift1",
      args: [
          "/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/bin/thrift1",
          "-I",
          "/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build",
          "--gen",
          "mstch_rust:cratemap=/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build/rust-shed/release/build/just_knobs_struct_services-0fde1c0be116e4b5/out/cratemap,include_prefix=/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build,types_crate=just_knobs_struct__types,clients_crate=just_knobs_struct__clients,services_crate=just_knobs_struct__services,serde",
          "--out",
          "/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build/rust-shed/release/build/just_knobs_struct_services-0fde1c0be116e4b5/out",
          "../just_knobs.thrift",
      ],
      create_pidfd: false,
  }'
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `just_knobs_struct v0.1.0 (/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build/rust-shed/source/shed/justknobs_stub/cached_config_thrift_struct)`
Caused by:
  process didn't exit successfully: `/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/build/rust-shed/release/build/just_knobs_struct-de24883db6915c5d/build-script-thrift_build` (exit status: 101)
```

Reviewed By: shayne-fletcher

Differential Revision: D54865629

fbshipit-source-id: 6b5db42e6d58eaa9bfcb8dcaac07f58711cd5398