autocargo/thrift: add support for rust_extra_srcs to fix mononoke OSS cargo build
Summary:
Add support for rust_extra_srcs to autocargo and rust shed thrift wrapper.  Copy extra sources to the cargo thrift build location so that the include!() can find them

Mononoke started using them in D63977688, which is causing [github CI Cargo based builds to fail](https://github.com/facebook/sapling/actions/runs/11329919951/job/31506538796) with `error[E0583]: file not found for module 'extra_thrift'`

Mononoke cargo build was also broken on missing scs_errors and scs_methods crate used from async_requests, hence the autocargo mapping update to include it in following diff D64541433

Reviewed By: andreacampi

Differential Revision: D64541434

fbshipit-source-id: 118508175e4168b15e4c99dd63a6eaa34ac10c5e