Support hostname in conda builds
Summary:
This is similar to D80722574 and allows the `hostname` library to be used in conda.

We need this change to resolve the following build error in the MTIA conda stack (when including ODS):

```
error[E0433]: failed to resolve: could not find `real_hostname` in the list of imported crates
  --> fbcode/common/rust/shed/hostname/src/lib.rs:31:14
   |
31 |         Ok(::real_hostname::get()?.to_string_lossy().into_owned())
   |              ^^^^^^^^^^^^^ could not find `real_hostname` in the list of imported crates

Target `fbcode//common/rust/shed/hostname:hostname` has unused dependencies:
    fbcode//common/rust/fbwhoami:fbwhoami: fbwhoami
error: aborting due to 1 previous error
```

Reviewed By: dtolnay

Differential Revision: D81330972

fbshipit-source-id: eeadc11124162808b83e7df431cc1e3d94de851b