Fix doc tests of all rust shed libraries
Summary:
The most common reason doc tests were failing in this directory was libraries wrapping a different library with the same crate name. This isn't supported by rustdoc; Cargo builds also can't handle it, so this isn't just a Buck thing.

```
# Cargo.toml

[package]
name = "repro"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
repro = { path = "repro" }
```

```
// src/lib.rs

pub use repro::*;
```

```
# repro/Cargo.toml

[package]
name = "repro"
version = "0.0.1"
edition = "2021"
```

```
// repro/src/lib.rs

// empty
```

`cargo build` and `cargo check` and `cargo test --lib` all work but `cargo test --doc` fails with:

```
error[E0464]: multiple candidates for `rlib` dependency `repro` found
 --> /home/dtolnay/git/testing/src/lib.rs:1:9
  |
1 | pub use repro::*;
  |         ^^^^^
  |
  = note: candidate #1: /home/dtolnay/git/testing/target/debug/deps/librepro-725729443e4c16bf.rlib
  = note: candidate #2: /home/dtolnay/git/testing/target/debug/deps/librepro-672f1a0fa094be50.rlib

error: aborting due to previous error

For more information about this error, try `rustc --explain E0464`.
error: doctest failed, to rerun pass `--doc`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name repro --test /home/dtolnay/git/testing/src/lib.rs -L dependency=/home/dtolnay/git/testing/target/debug/deps -L dependency=/home/dtolnay/git/testing/target/debug/deps --extern repro=/home/dtolnay/git/testing/target/debug/deps/librepro-725729443e4c16bf.rlib --extern repro=/home/dtolnay/git/testing/target/debug/deps/librepro-672f1a0fa094be50.rlib -C embed-bitcode=no --error-format human` (exit status: 1)
```

That's because rustdoc's command line interface exposes no way to disambiguate the `--extern=repro=...` referring to the doc tests' dependency on the crate that is being documented, vs the `--extern=repro=...` referring to the dependency whose name is the same thing.

Reviewed By: zertosh

Differential Revision: D43511516

fbshipit-source-id: 11a8b62e2cf74715193b6d98d4e808cede6154b2