Backport tonic PR 2423 to 0.12.3
Summary:
This fixes the "invalid dns name" error in {D94301757}.

```lang=log,counterexample
$ wa env pgwd3.atn
Mounting pgwd0003.atn:/home/whatsapp to /tmp/.tmpHkJ3AH/mounts/pgwd0003.atn
Error: transport error

Caused by:
    invalid dns name
```

Reviewed By: diliop

Differential Revision: D95281730

fbshipit-source-id: a5f16c128b6eedc87bfac8d554913ab33135b6b6