Add support for Mocks crate generation context
Summary:
This diff by itself has no effect. It only has an effect once fbcode_macros begins to emit a crate with `autocargo = {"thrift": {"gen_context": "mocks"}}` which happens in D56451421.

But before that can happen, the `autocargo` MSDK needs to be rebuilt to include this diff, otherwise autocargo fails with:

```lang=text,counterexample
Error: While reading file buck-out/v2/gen/fbcode/78fe5c5af16d7c0a/eden/mononoke/git/packfile/if/__packfile-thrift-rust-mocks-rust-manifest__/out/manifest.json

Caused by:
    unknown variant `mocks`, expected one of `types`, `clients`, `services` at line 1 column 1010
```

Reviewed By: shayne-fletcher

Differential Revision: D56451422

fbshipit-source-id: f9ee723c123986e50aec00ff91e1be97848bb927