fix windows build setuptools error
Summary:
X-link: https://github.com/facebook/watchman/pull/1316

The upgrade of setuptools in D79195099 broke pywatchman  build,  Github windows CI erroring with  `AttributeError: module 'setuptools.dist' has no attribute 'check_test_suite'` https://github.com/facebook/watchman/actions/runs/19440507973/job/55622405533#step:131:1188 .  It was only affecting windows as only windows CI is building dependencies form source, the others use system dependencies.

Fix by pinning watchman to the previous setuptools version

Fix to help iterate locally:
*  fix the cargo.py remove behaviour to use rmtree_more.  This fixes repeat local builds while debugging. After the first build was getting `PermissionError: [WinError 5] Access is denied: 'Z:\build\fbthrift\source\.git\objects\pack\pack-250eb41d409d8c0f512fdb239d0225fa35d50c3d.idx'`

Reviewed By: bigfootjon

Differential Revision: D87655865

fbshipit-source-id: 8948b0ffe38f304fa96051bf6ac3a0455ef1a16e